version: '3.7'

services:
  node:
    container_name: node
    build: ./
    user: node
    networks:
      - backend
    expose:
      - 5000
    ports:
      - ${PORT}:5000
    volumes:
      - ./:/home/node
      - /home/node/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres-volume:
networks:
  backend:
    driver: bridge
